events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name mainn.web.id www.mainn.web.id;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mainn.web.id www.mainn.web.id;

        ssl_certificate /etc/letsencrypt/live/mainn.web.id/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mainn.web.id/privkey.pem;

        location / {
            proxy_pass http://web-app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name monitor.mainn.web.id;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name monitor.mainn.web.id;

        ssl_certificate /etc/letsencrypt/live/mainn.web.id/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mainn.web.id/privkey.pem;

        location / {
            proxy_pass http://uptime-kuma:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}