name: Deploy to VPS

on:
  push:
    branches:
      - main # Akan berjalan otomatis setiap kamu melakukan git push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Eksekusi Perintah di VPS Lewat SSH
        uses: appleboy/ssh-action@1.0.3
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USERNAME }}"
          password: "${{ secrets.SSH_PASSWORD }}"
          script: |
            cd /app/uas-web
            git pull origin main
            docker compose up -d --build
